### ISSUE TITLE
Image in the `README.md` is inaccessible

### ISSUE THREAD

**Issue by sskras** [ladislav-zezula/FileTest#21]
![image](https://github.com/ladislav-zezula/FileTest/assets/7887758/4f64e882-01ec-42c1-a28a-df564e4c7e84)

Here is the broken URL:
https://camo.githubusercontent.com/1875d3123671e3dfc24af5b1d3f543d1b8bd80bf68c4ad24adcb38fa12a07608/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f32393636383237352f66696c65746573742e706e67

Not sure what it was pointing to.

**Comment by ladislav-zezula** [comment]
Fixed in https://github.com/ladislav-zezula/FileTest/commit/3dd6ae860428c9a94e89f7684c8998f0ce185dab.

**Comment by sskras** [comment]
Ah, the broken URL was different:
```diff

-![Interactive File System Test Tool](https://dl.dropboxusercontent.com/u/29668275/filetest.png)
+![Interactive File System Test Tool](http://www.zezula.net/images/tools/filetest_001.png)

```

I was checking at the wrong level. Thanks!
