### ISSUE TITLE
Handling more ACE types

### ISSUE THREAD

**Issue by diversenok** [ladislav-zezula/FileTest#23]
Hi, @ladislav-zezula, I see you added support for handling callback ACEs in https://github.com/ladislav-zezula/FileTest/commit/c73dccbb5f25657ca3bd666917769a188f0a724b, which is awesome!

Some time ago I also did [something similar](https://twitter.com/diversenok_zero/status/1688609841651081216) for my tool. I am a bit busy right now to make a PR for FileTest with support for even more obscure ACE types, but I hope I can at least help by documenting some things here, in case you plan to expand on the topic.

### Compound ACEs
`ACCESS_ALLOWED_COMPOUND_ACE_TYPE` (4) is somewhat special since it has a unique ACE structure and purpose. It stores two SIDs: Client SID and Server SID, and, effectively, performs two access checks at once:
1. It tests the caller's effective (thread, if present, otherwise, process) token against the Client SID.
2. It tests the caller's process token against the Server SID, ignoring impersonation.

Here is the ACE definition:
```c
#define COMPOUND_ACE_IMPERSONATION 1

typedef struct _COMPOUND_ACCESS_ALLOWED_ACE
{
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    USHORT CompoundAceType; // always COMPOUND_ACE_IMPERSONATION 
    USHORT Reserved;
    ULONG SidStart; // Server SID
    // Client SID follows
} COMPOUND_ACCESS_ALLOWED_ACE, *PCOMPOUND_ACCESS_ALLOWED_ACE;
```

### Resource Attribute ACEs
`SYSTEM_RESOURCE_ATTRIBUTE_ACE_TYPE` (0x12) is a SACL ACE that attaches key-value attributes to the object and allows customizing callback ACEs. Resource attributes are very similar to token security attributes and can be referenced in callback ACEs via the `@RESOURCE.` prefix (which I'm sure you saw). The `SYSTEM_RESOURCE_ATTRIBUTE_ACE` is documented in SDK and has the extra data for the attributes stored in a relative format. It can be accessed via `ATTRIBUTE_SECURITY_INFORMATION`.

I'm not sure how difficult it would be to display resource attributes since they can be quite lengthy. But at least it might be a good idea to recognize this ACE type. For testing purposes, you can find such ACE attached to the Downloads folder on Windows 10/11.

### Scoped Policy ID ACEs
I don't know much about `SYSTEM_SCOPED_POLICY_ID_ACE_TYPE` (0x13) aside from that it follows the simple ACE structure, needs `S-1-17-*` SIDs, and can be accessed via `SCOPE_SECURITY_INFORMATION`.

### Trust Label ACEs
`SYSTEM_PROCESS_TRUST_LABEL_ACE_TYPE` (0x14) is a SACL ACE that uses a normal (type-specific) access mask and a `S-1-19-x-y` SID to specify the required process protection level. Caller's with lower level will be limited to the subsets of rights specified in the ACE. This type of ACEs can be accessed via `PROCESS_TRUST_LABEL_SECURITY_INFORMATION`.

Adjusting FileTest to show trust labels should be straightforward. For testing, see `C:\Program Files\WindowsApps\<any folder>`.

### Access Filter ACEs
`SYSTEM_ACCESS_FILTER_ACE_TYPE` (0x15) has a structure of a callback ACE and introduces an additional layer of access checks on the object by filtering all access attempts against a condition. Callers that don't pass the check are limited to the subset of the specified rights. This ACE can operate in two modes:
1. When `Flags` don't contain `TRUST_PROTECTED_FILTER_ACE_FLAG` (0x40), the SID must be Everyone, which means the system simply filters access according to the callback condition.
2. When `Flags` contain `TRUST_PROTECTED_FILTER_ACE_FLAG`, the SID must represent a trust level (`S-1-19-x-y`). In this case, the system performs access filtration according to the condition only when the caller's trust is lower. In other words, a trust-protected Access Filter ACE works as a *Trust Label Callback ACE* would.

You can query/set these ACEs via `ACCESS_FILTER_SECURITY_INFORMATION`. Despite the intricate logic, parsing them works identical to other callback ACEs. One slight caveat is that `TRUST_PROTECTED_FILTER_ACE_FLAG` shares its value with `SUCCESSFUL_ACCESS_ACE_FLAG`.

**Comment by ladislav-zezula** [comment]
What a work. I didn't have much time for it and I also played with it a bit, hence it took so long.
https://github.com/ladislav-zezula/FileTest/pull/24

Some ACE types (such as `SYSTEM_ACCESS_FILTER_ACE`) are hard to even set - to my understanding, it requires a trusted process to even set them. FileTest can also add those ACEs to DACL - the operating system doesn't protest, so these ACEs can be tested in DACL instead in SACL.

**Comment by diversenok** [comment]
Wow, great job!

As for filter ACEs - applying them only requires a dominating trust label in the caller's token when used in conjunction with `TRUST_PROTECTED_FILTER_ACE_FLAG`. Without this flag (when the SID must be Everyone), they can be set by anybody. I see that the current implementation parses them correctly but, for some reason, fails to set them (even without modification) with `STATUS_INVALID_ACL`. I'll try to debug it to see what's going on. In the meantime, if you need another tool to test it against, [TokenUniverse](https://github.com/diversenok/TokenUniverse) can set non-trust access filter ACEs (see "Tools -> Check access to..." menu in the main window).

![image](https://github.com/ladislav-zezula/FileTest/assets/30962924/5907f165-7455-4e1c-a9fb-831b05a6e820)

**Comment by ladislav-zezula** [comment]
> I'll try to debug it to see what's going on

Don't: https://github.com/ladislav-zezula/FileTest/pull/25
