### ISSUE TITLE
Невозможно управлять FileTest через консоль, что свою очередь усложняет использование в автоматизаций

### ISSUE THREAD

**Issue by devhazhi** [ladislav-zezula/FileTest#7]

**Comment by ladislav-zezula** [comment]
Yes. FileTest is a GUI tool, and it's not indended for any kind of automation. If you want to automate,  get some NTDLL wrapper for Python and do it there. Or, write a C++ program.

**Comment by devhazhi** [comment]
thank you, i got it, just like that use ntdll https://www.pinvoke.net/default.aspx/ntdll.ntcreatefile
